
#profiles文件查找模式 application-名字:
server:
    port: 8080
    context-path: /mini


entitymanager:
    packagesToScan: com.ssea.miniapp


spring:
    #mysql: create database test in mysql
    datasource:
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&autoReconnect=true
        username: root
        password: admin
        driver-class-name: com.mysql.jdbc.Driver
    #hibernate
    jpa:
      properties:
          hibernate:
              hbm2ddl:
                  #validate create create-drop update
                  auto: update
              dialect: org.hibernate.dialect.MySQL5Dialect

    #redis
    redis:
      database: 0
      host: localhost
      port: 6379
      # 连接超时时间（毫秒）
      timeout: 0
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #密码默认为空
        password:

